tutorial/polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'(?P<pk>\d+)/results$', views.results, name='results'),
    url(r'^form/(?P<pk>(\w|\W)*)$', views.form_test, name='forms'),
    # urlに入力文字列が入る
]

tutorial/tutorial/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from polls.views import index

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^$', index, name='index'),
]

tutorial/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class QuestionQuerySet(models.query.QuerySet):  # QuerySet拡張用のクラス
    def is_published(self):
        return self.filter(pub_date__lte=timezone.now())


class Question(models.Model):
    class Meta:
        verbose_name = '質問'
        verbose_name_plural = '質問の複数形'
        ordering = ['question_text', 'pub_date']

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # 拡張されたQuerySetを使う様に変更
    objects = models.Manager.from_queryset(QuestionQuerySet)()

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= \
               self.pub_date >= \
               timezone.now() - datetime.timedelta(days=1)
        # 条件に「公開日時が現在より前か」を追加
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_discription = '24時間以内の公開'

    @classmethod
    def get_published_data(cls):  # 新たに追加したメソッド1
        return cls.objects.filter(pub_date__lte=timezone.now())

    @classmethod
    def get_published_data_extend_queryset(cls):  # 新たに追加したメソッド2
        return cls.objects.is_published()


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

tutorial/polls/forms.py
from django import forms


class MyForm(forms.Form):  # MyForm Class はチュートリアル5-2終了時のまま
    text = forms.CharField(max_length=100, required=False, label='テキスト')


class VoteForm(forms.Form):
    choice = forms.ModelChoiceField(
        queryset=None,               # 選択肢を保持する
        label='選択肢',               # フォームにつけるラベル
        widget=forms.RadioSelect(),  # フォームの形式
        empty_label=None,            # 「何も選ばない」という選択肢は無し
        error_messages={             # エラーメッセージ
            'required': "選択肢が何も選ばれていません。",
            'invaid_choice': "無効な選択肢です。",
        }
    )

    def __init__(self, question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['choice'].queryset = question.choice_set.all()

    def vote(self):  # 投票処理
        assert(self.is_valid())
        choice = self.cleaned_data['choice']
        choice.votes += 1
        choice.save()

tutorial/polls/views.py
from django.shortcuts import render
from django.utils.html import mark_safe
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import resolve_url
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages  # messagesを使う為にimport

from .models import Question, Choice

from django.views.generic import DetailView, ListView, FormView
from .forms import MyForm, VoteForm


class FormTest(FormView):
    form_class = MyForm
    template_name = 'polls/form.html'
    success_url = reverse_lazy('polls:index')


class Detail(SingleObjectMixin, FormView):
    model = Question
    form_class = VoteForm
    context_object_name = 'question'
    template_name = 'polls/detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['question'] = self.object
        return kwargs

    def form_valid(self, form):  # このメソッドを変更
        form.vote()
        choice = form.cleaned_data['choice']  # 投票したデータを変数choiceに代入
        messages.success(self.request, '"%s"に投票しました' % choice)
        # choiceの内容をmessages.success関数で表示
        return super().form_valid(form)

    def get_success_url(self):
        return resolve_url('polls:results', self.kwargs['pk'])


class Index(ListView):
    template_name = 'polls/index.html'
    queryset = Question.objects.all()
    context_object_name = 'questions'


class Results(DetailView):
    template_name = 'polls/results.html'
    model = Question
    context_object_name = 'question'

form_test = FormTest.as_view()
detail = Detail.as_view()
index = Index.as_view()
results = Results.as_view()

tutorial/polls/templates/polls/detail.html
{% extends "polls/polls_base.html" %}

{% block contents %}
    <h1>{{ question.question_text }}</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" Value="Vote" />
    </form>
    <a href="{% url 'polls:index' %}">一覧画面へ</a><br />
{% endblock contents %}

tutorial/polls/templates/polls/form.html
{% extends "polls/polls_base.html" %}

{% block contents %}
    <p>{{ message }}</p>
    <form action="" method="POST">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="送信"/>
    </form>
{% endblock contents %}

tutorial/polls/templates/polls/index.html
{% extends "polls/polls_base.html" %}

{% block contents %}
    <table border="1" class="table table-striped">
      <tr><th>質問内容</th><th>リンク</th></tr>
      {% for question in questions %}
      <tr>
        <td>{{ question.question_text }}</td>
        <td><a href="{% url 'polls:detail' question.pk %}">投票画面へ</a></td>
      </tr>
      {% endfor %}
    </table>
{% endblock contents %}

tutorial/polls/templates/polls/polls_base.html
{% extends "base.html" %}

{% block nav_polls %}active{% endblock %}

tutorial/polls/templates/polls/results.html
{% extends "polls/polls_base.html" %}

{% block contents %}
    <h1>{{ question.question_text }} -投票結果-</h1>
    <ul>
      {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
      {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">もう一度投票する</a><br />
{% endblock contents %}

tutorial/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style type="text/css">
body {
  padding-top: 50px;
}
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Djangoチュートリアル</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{% block nav_polls %}{% endblock %}"><a href="{% url 'polls:index' %}">polls(投票アプリ)</a></li>
            <li class=""><a href="{% url 'admin:index' %}">admin(管理者サイト)</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      {% if messages %}  <!--ここから追加-->
      {% bootstrap_messages messages %}  <!--django-bootstrap3を使ってお洒落に表示-->
      {% endif %}        <!--ここまで追加-->
      {% block contents %}{% endblock %}
    </div><!-- /.container -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>